title: Adina Stoll
subtagline: Software Engineer @Microsoft
# tagline: Sharing the small learnings, big learnings, but mainly the ones in between.
description: 'Sharing the small learnings, big learnings, and the ones in between. Philosophy of Life - CL (Continous Learning).'
cover: /cover.jpg

categories_path: /categories/
tags_path: /tags/
